-- BEZERO 

DROP TRIGGER IF EXISTS BEZERO_ERREGISTRO_KONTROLA;

DELIMITER // 
CREATE TRIGGER BEZERO_ERREGISTRO_KONTROLA
AFTER INSERT ON BEZERO
FOR EACH ROW 
BEGIN
	INSERT INTO TXERTAKETAK_ETA_EZABAKETAK_KONTROLA (TXERTAKETAK) VALUES (CONCAT('BEZERO BERRIA: ', NEW.ERABILTZAILEA, ' - TXERTATU EGIN DA ', CURDATE(), ' DATAREKIN'));
END // 
DELIMITER ;

DROP TRIGGER IF EXISTS BEZERO_EZABAKETAK_KONTROLA;

DELIMITER // 
CREATE TRIGGER BEZERO_EZABAKETAK_KONTROLA
AFTER DELETE ON BEZERO
FOR EACH ROW 
BEGIN
	INSERT INTO TXERTAKETAK_ETA_EZABAKETAK_KONTROLA (EZABAKETAK) VALUES (CONCAT('BEZERO EZABAKETA: ', OLD.IZENA, ' ', OLD.ABIZENA,' IZEN ABIZENAREKIN ETA ', OLD.ERABILTZAILEA, ' - ERABILTZAILEAREKIN EZABATU EGIN DA ', CURDATE(), ' DATAREKIN'));
END // 
DELIMITER ;




-- SALTZAILE
DROP TRIGGER IF EXISTS SALTZAILE_ERREGISTRO_KONTROLA;

DELIMITER // 
CREATE TRIGGER SALTZAILE_ERREGISTRO_KONTROLA
AFTER INSERT ON LANGILE
FOR EACH ROW 
BEGIN
	INSERT INTO TXERTAKETAK_ETA_EZABAKETAK_KONTROLA (TXERTAKETAK) VALUES (CONCAT('SALTZAILE BERRIA: ', NEW.IZENA, ' ',NEW.ABIZENA, ' - TXERTATU EGIN DA ', CURDATE(), ' DATAREKIN'));
END // 
DELIMITER ;

DROP TRIGGER IF EXISTS SALTZAILE_EZABAKETAK_KONTROLA;

DELIMITER // 
CREATE TRIGGER SALTZAILE_EZABAKETAK_KONTROLA
AFTER DELETE ON LANGILE
FOR EACH ROW 
BEGIN
	INSERT INTO TXERTAKETAK_ETA_EZABAKETAK_KONTROLA (EZABAKETAK) VALUES (CONCAT('SALTZAILE EZABAKETA: ', OLD.IZENA, ' ', OLD.ABIZENA,' IZEN ABIZENAREKIN EZABATU EGIN DA ', CURDATE(), ' DATAREKIN'));
END // 
DELIMITER ;



-- TAULAK

DROP TABLE IF EXISTS TXERTAKETAK_ETA_EZABAKETAK_KONTROLA; 

CREATE TABLE TXERTAKETAK_ETA_EZABAKETAK_KONTROLA (
	TXERTAKETAK VARCHAR (255),
    EZABAKETAK VARCHAR (255)
);

DROP TABLE IF EXISTS EGUNERAKETAK_KONTROLA;

CREATE TABLE EGUNERAKETAK_KONTROLA (
	KONTROLA VARCHAR(999)
);


-- EGUNERAKETAK KONTROLA

DROP TRIGGER IF EXISTS BEZERO_DATU_ALDAKETAK;

DELIMITER //
CREATE TRIGGER BEZERO_DATU_ALDAKETAK
AFTER UPDATE ON BEZERO
FOR EACH ROW
BEGIN
		INSERT INTO EGUNERAKETAK_KONTROLA(KONTROLA) 
        VALUES (CONCAT('Bezero: ', OLD.IZENA, ' ', OLD.ABIZENA,' ', OLD.HELBIDEA,' ', OLD.EMAILA, ' ', OLD.ERABILTZAILEA,' ', OLD.PASAHITZA,' ', OLD.NAN, ' -rekin aldatu du informazioa honetara: ', 
        NEW.IZENA, ' ', NEW.ABIZENA,' ', NEW.HELBIDEA,' ', NEW.EMAILA, ' ', NEW.ERABILTZAILEA,' ', NEW.PASAHITZA,' ', NEW.NAN));
END //
DELIMITER ;

DROP TRIGGER IF EXISTS SALTZAILE_DATU_ALDAKETAK;

DELIMITER //
CREATE TRIGGER SALTZAILE_DATU_ALDAKETAK
AFTER UPDATE ON LANGILE
FOR EACH ROW
BEGIN
		INSERT INTO EGUNERAKETAK_KONTROLA(KONTROLA) 
        VALUES (CONCAT('Saltzaile: ', OLD.IZENA, ' ', OLD.ABIZENA,' ', OLD.EMAILA,' ', OLD.TELEFONOA, ' ', OLD.SOLDATA,' ', OLD.KONTRATAZIO_DATA,' ', OLD.ID_NAGUSI, ' -rekin aldatu du informazioa honetara: ', 
		NEW.IZENA, ' ', NEW.ABIZENA,' ', NEW.EMAILA,' ', NEW.TELEFONOA, ' ', NEW.SOLDATA,' ', NEW.KONTRATAZIO_DATA,' ', NEW.ID_NAGUSI));
END //
DELIMITER ;

CREATE OR REPLACE VIEW BISTA_EGUNERAKETAK AS SELECT * FROM EGUNERAKETAK_KONTROLA;
CREATE OR REPLACE VIEW BISTA_TXERTAKETAK_EZABAKETAK AS SELECT * FROM TXERTAKETAK_ETA_EZABAKETAK_KONTROLA;

	