CREATE DEFINER=`root`@`localhost` PROCEDURE `SALTZAILE_ALDAKETA`(
    IN SARRERA_ID INT, 
    IN SARRERA_IZENA VARCHAR(100), 
    IN SARRERA_ABIZENA VARCHAR(100), 
    IN SARRERA_ERABILTZAILEA VARCHAR(100), 
    IN SARRERA_PASAHITZA VARCHAR(100), 
    IN SARRERA_EMAILA VARCHAR(100), 
    IN SARRERA_TELEFONOA VARCHAR(100), 
    IN SARRERA_SOLDATA INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;
    
    START TRANSACTION;
    
    -- Actualizar LANGILE
    UPDATE LANGILE SET 
        IZENA = SARRERA_IZENA, 
        ABIZENA = SARRERA_ABIZENA, 
        EMAILA = SARRERA_EMAILA, 
        TELEFONOA = SARRERA_TELEFONOA, 
        SOLDATA = SARRERA_SOLDATA 
    WHERE ID = SARRERA_ID;

    -- Actualizar SALTZAILE
    UPDATE SALTZAILE SET
        ERABILTZAILEA = SARRERA_ERABILTZAILEA, 
        PASAHITZA = SARRERA_PASAHITZA 
    WHERE ID = SARRERA_ID;
    
    COMMIT;
    
END